### ISSUE TITLE
Ignore imperative matches in the rest of the commit message

### ISSUE THREAD

**Issue by masimplo** [tommarshall/git-good-commit#6]
I am constantly having an issue committing with messages that do start with imperative but contain non imperative ones along the message. For instance writing something like:

- Fix a merge issue causing an error in login
- Change the order of some fixes
- Add code that removes the known issue

will trigger rule number 5 and give an error message. Shouldn't the imperative rule only match the first word?

**Comment by tommarshall** [comment]
Hi @masimplo. Thanks for raising this. I agree. I've been running into the same issue.

**Comment by tommarshall** [comment]
This is fixed in v0.5.0.

You can update to v0.5.0 by repeating the [installation instructions in the README](https://github.com/tommarshall/git-good-commit#installation).
